### ISSUE TITLE
Issue with Media center's  Audio player options.

### ISSUE THREAD

**Issue by vineetasharma** [BuildFire/pluginMediaCenterManualEntries#22]
![mediaplayer](https://cloud.githubusercontent.com/assets/7790663/9897942/9f301b20-5c6b-11e5-8af7-f6b27b7920e1.png)

**Comment by nathankeating** [comment]
Since this is the audio player inside the media center plugin, here are the answers to your questions:
1. Can we remove the playlist button?
No. When the app user clicks on this button, it should take them to their own personal playlist that they have created.

2. Can we remove the shuffle button?
I would like to clarify functionality here... Let's use the following scenario:
- An app USER enters a media center plugin on the app called "Cool Music Album"
- Inside of this plugin, the app OWNER has created a list of ten items (Song 1, Song 2, Song 3, etc.). NOTE: This is not to be confused with the app USER's personal playlist.
- The app user then clicks on the item called "Song 3" to go into the song details page
- Once inside the item, the user clicks "Listen"

Here's what should happen:
- The media center's audio player should appear and start playing the track
- The media center's audio player would use the item list that the app OWNER has created to move through the songs when the current track is finished playing or the user clicks the next or back buttons. If the app USER has shuffle disabled, it would move through them in sequence (e.g. Song 3 -> Song 4 -> Song 5 -> etc.). If the app user has shuffle enabled, it will shuffle through the tracks randomly (e.g. Song 3 -> Song 7 -> Song 1 -> etc.).
NOTE: If there is a track that does not have audio, the player should skip it. For example, let's assume that all of the songs have audio except for Song 8. If the app user started at Song 7 and has shuffle disabled, then when the current track is finished playing or the user clicks the next button, it should skip to Song 9 (the next available item that has audio)

**Comment by vineetasharma** [comment]
Thanks Nathan.
